####################################
######     Global start     ######
####################################
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://loryrosenberg.com/' #  7277783  the base hostname & protocol for your site, e.g. http://example.com
locale: 'en_US'

author:
  name: Lory Rosenberg

# paginate
paginate: 6
paginate_path: '/blog/page:num/'

keep_files:
  - .git
  - .svn
encoding: 'utf-8'
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:slug/
  pages:
    output: true
    permalink: /:collection/:slug/

# Defaults
defaults:
  # _posts
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: '' # we can not defile path /blog/index.html for pagination
      type: pages
    values:
      layout: page

timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# disqus comment
disqus_shortname: anvodstudio-demo

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives

# jekyll archive
jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    category: category-archive
    tag: tag-archive
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'

####################################
######      Global end      ######
####################################
# Ajax Contact form
# go to https://formspree.io/ for signup
#
formspree_id: 'mrgdpbok'

# mailchimp SUBSCRIVE FORM
mailchimp:
  user-id: 'c4e151b63d84a9bac731252a2'
  list-id: 'ca518aaa14'
  username: 'jekylltemplate.us5'

## leaflet map
map:
  lat: '40.7128'
  lng: '-74.0060'

# SEO Related
google_site_verification: ''
bing_site_verification: ''
yandex_site_verification: ''
naver_site_verification: ''

# Social Sharing
twitter:
  username: ''
facebook:
  username: ''
  app_id: ''
  publisher: ''
og_image: 'assets/images/about/1695137623297.jpeg' # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: '' # Person or Organization (defaults to Person)
  name: '' # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: ''
    anonymize_ip: true # true, false (default)
